name: app_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - flask=2.1.3
  - numpy=1.22.3
  - pandas=1.4.3
  - python=3.9.1
  - scikit-learn=1.0.2
  - pip
  - pip:
    - flask_sqlalchemy
    - flask_cors
    - dotenv
    - rich
    - mysql-connector-python
    - pymysql

#Flask==2.2.2
#Flask-Cors==3.0.10
#Flask-SQLAlchemy==2.5.1
#Flask-Testing==0.8.1
#pipreqs==0.4.11
#requests==2.28.1
#SQLAlchemy==1.4.43
#mysql-connector-python==8.1.0